// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLUHwnihLlb_7IIoqpmLxoDgJgb5ef_Z0',
    appId: '1:713544044208:android:11068bb2b52418e387b575',
    messagingSenderId: '713544044208',
    projectId: 'rada-logistics-95953',
    databaseURL: 'https://rada-logistics-95953-default-rtdb.firebaseio.com',
    storageBucket: 'rada-logistics-95953.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVD6f5_otK4K0kiZrFLs7E4H7eOsEB_6Y',
    appId: '1:713544044208:ios:d8e996f214fccfdf87b575',
    messagingSenderId: '713544044208',
    projectId: 'rada-logistics-95953',
    databaseURL: 'https://rada-logistics-95953-default-rtdb.firebaseio.com',
    storageBucket: 'rada-logistics-95953.firebasestorage.app',
    iosClientId: '713544044208-02g8gmc24dpronf10d1um06d7jhmnlv4.apps.googleusercontent.com',
    iosBundleId: 'com.example.radaRider',
  );

}